### PR TITLE
Fix Migrator with joined/imported fields

### LINKED ISSUE #1226: Migrator::create() adds Fields from Join to Model table
Some Code from my application (Tour Model):
```php
        $ttJoin = $this->leftJoin('tour_type', ['masterField' => 'tour_type_id']);

        $ttJoin->addField('activity_id', ['system' => true]);
```
When using `Migrator::create()` to create a table for this Model, the field `activity_id` is added.

I will provide a minimal test to reproduce.

### PR DESCRIPTION
**Pull request by PhilippGrashoff**
fix #1226

Currently, migrator does create Model fields that are defined by `Model::leftJoin()` within the model table when exexuting `Migrator::create()`. 
As these fields are defined by a weak join, they should not be created within the model table but their values should be loaded from the joined table on load.

### CODE REVIEW

**Comment by PhilippGrashoff** [comment]
PR ready to merge

File: src/Schema/Migrator.php [hunk 1]
```diff
@@ -293,24 +293,27 @@ public function setModel(Model $model): Model
             if ($field->neverPersist || $field instanceof SqlExpressionField) {
                 continue;
             }
+            if ($field->hasJoin()) {
+                continue;
+            }
 
             if ($field->shortName === $model->idField) {
-                $refype = self::REF_TYPE_PRIMARY;
+                $refType = self::REF_TYPE_PRIMARY;
```
Comment (mvorisek) [inline src/Schema/Migrator.php:302]: 👍

File: src/Schema/Migrator.php [hunk 2]
```diff
@@ -293,24 +293,27 @@ public function setModel(Model $model): Model
             if ($field->neverPersist || $field instanceof SqlExpressionField) {
```
Comment (mvorisek) [inline src/Schema/Migrator.php]:
```suggestion
            if (
                $field->neverPersist
                || $field->hasJoin()
                || $field instanceof SqlExpressionField
            ) {
```

File: tests/Schema/MigratorTest.php [hunk 3]
```diff
@@ -231,7 +234,11 @@ public function testCharacterTypeFieldLong(string $type, bool $isBinary, int $le
 
         // functional test for Expression::escapeStringLiteral() method
         $strRaw = $model->getPersistence()->typecastSaveField($model->getField('v'), $str);
-        $strRawSql = \Closure::bind(static fn () => $model->expr('')->escapeStringLiteral($strRaw), null, Expression::class)();
+        $strRawSql = \Closure::bind(
```
Comment (mvorisek) [inline tests/Schema/MigratorTest.php]: We would have to do this CS change consistently across all repos which is not easily possible, as `\Closure::bind` is very often used inside some expr. (like `if`)

please revert these CS changes - if they were done by your IDE, I advise you to disable them for atk4/* repos at least

File: tests/Schema/MigratorTest.php [hunk 4]
```diff
@@ -326,7 +344,8 @@ public function testIntrospectTableToModelBasic(): void
         $expectedFields = [];
         foreach ($creatingMigrator->table->getColumns() as $column) {
             $expectedFields[$column->getName()] = [
-                'type' => Type::getTypeRegistry()->lookupName($column->getType()), // TODO simplify once https://github.com/doctrine/dbal/pull/6130 is merged
+                'type' => Type::getTypeRegistry()->lookupName($column->getType()),
```
Comment (mvorisek) [inline tests/Schema/MigratorTest.php]: this CS change is to be reverted as well - and never place comment below

File: tests/Schema/MigratorTest.php [hunk 5]
```diff
@@ -433,3 +459,14 @@ protected function init(): void
         $this->hasMany('Users', ['model' => [TestUser::class], 'ourField' => 'id', 'theirField' => 'main_role_id']);
     }
 }
+
+class TestUserWithJoin extends TestUser
+{
+    #[\Override]
+    protected function init(): void
+    {
+        parent::init();
```
Comment (mvorisek) [inline tests/Schema/MigratorTest.php:476]:
```suggestion
        parent::init();

```

File: tests/Schema/MigratorTest.php [hunk 6]
```diff
@@ -400,6 +419,13 @@ public function testIntrospectTableToModelSetPersistence(): void
         self::assertTrue($model->issetPersistence());
         self::assertSame(['id', 'a'], array_keys($model->getFields()));
     }
+
+    public function testJoinFieldsAreNotCreated(): void
+    {
+        $migrator = $this->createMigrator(new TestUserWithJoin($this->db))->create();
+        $tableColumns = $migrator->table->getColumns();
+        self::assertArrayNotHasKey('role_name', $tableColumns);
```
Comment (mvorisek) [inline tests/Schema/MigratorTest.php]:
```suggestion
        $model = new TestUserWithJoin($this->db);
        $migrator = $this->createMigrator($model);
        self::assertSame(['todo'], array_keys($migrator->table->getColumns()));
        $migrator->create();
        
        $model = $this->createMigrator()->introspectTableToModel('user');
        self::assertSame(['todo'], array_keys($model->getFields()));
```

this will test if the DB fields are constructed correctly and also then if created correctly

**Comment by mvorisek** [comment]
Thank you, makes sense!

**Comment by PhilippGrashoff** [comment]
Thanks for improving the PR. I only made the CS because the github workflow complained about it.
