### PR TITLE
Fix array persistence data error

### LINKED ISSUE #245: Array Persistence without table name ignores first record
Consider this example:

``` php
    $my_array = [
        ['name'=>'Vinny', 'surname'=>'Sihra', 'birthdate'=>new \DateTime('1973-02-03')],
        ['name'=>'Zoe', 'surname'=>'Shatwell', 'birthdate'=>new \DateTime('1958-08-21')],
        ['name'=>'Darcy', 'surname'=>'Wild', 'birthdate'=>new \DateTime('1968-11-01')],
        ['name'=>'Brett', 'surname'=>'Bird', 'birthdate'=>new \DateTime('1988-12-20')],
    ];
    $goodData = ['data'=>$my_array];

    $m = new Model(new Persistence_Array($goodData), 'data');
    $m->addField('name');
```

When model initialized like that, executing foreach works well:

``` php
    foreach($m as $junk) {
        echo $m['name']."\n";
    }
```

This will result in output:

```
Vinny
Zoe
Darcy
Brett
```

Next change those two lines:

``` php
    $goodData = $my_array;
    $m = new Model(new Persistence_Array($goodData));
```

The Persistence_Array supports no-table arrays like that, however it fails to load values for the first column resulting in output:

```
  (null here)
Zoe
Darcy
Brett
```

### PR DESCRIPTION
**Pull request by DarkSide666**
* fix data[0] = &array() error
* fix #245

### CODE REVIEW

**Comment by romaninsh** [comment]
I don't think it actually addresses #245. Because everything works with table.

**Comment by DarkSide666** [comment]
It does. See skype.

File: src/Model.php [hunk 1]
```diff
@@ -272,11 +272,7 @@ public function __construct($persistence = null, $defaults = [])
             $persistence = null;
         }
 
-        foreach ($defaults as $key => $val) {
-            if ($val !== null) {
-                $this->$key = $val;
-            }
-        }
+        $this->setDefaults($defaults);
```
Comment (romaninsh) [inline src/Model.php]: fix to ['table'=>$defaults] on line 267
