### PR TITLE
Fix model OR condition typecast

### LINKED ISSUE #474: addCondition() OR case does not work with DateTime object
Hi,
I just noticed that this code does not work:
```
            $messages->addCondition([
                ['created_date', '>=', $maxInPast], //$maxInPast is a DateTime object
                ['never_invalid', 1]
            ]);
```
It leads to this exception:
```
atk4\dsql\Exception: Value cannot be converted to SQL-compatible expression 
              field: atk4\data\Field ()
               cond: ">="
              value: Object DateTime
--[ Stack Trace ]
ml/PMRAtk/vendor/atk4/dsql/src/Query.php: 625  - atk4\dsql\Exception atk4\core\Exception::__construct()
                                        :      - atk4\dsql\Query_MySQL atk4\dsql\Query::where
                                        (atk4\data\Field (), ">=", Object DateTime)
ml/PMRAtk/vendor/atk4/dsql/src/Query.php: 562  call_user_func_array()
vendor/atk4/data/src/Persistence/SQL.php: 364  - atk4\dsql\Query_MySQL atk4\dsql\Query::where()
vendor/atk4/data/src/Persistence/SQL.php: 582  - atk4\data\Persistence\SQL atk4\data\Persistence\SQL::initQueryConditions()
ml/PMRAtk/vendor/atk4/data/src/Model.php:2178  - atk4\data\Persistence\SQL atk4\data\Persistence\SQL::action()
ests/phpunit/Data/MessageForUserTest.php: 180  - PMRAtk\Data\MessageForUser atk4\data\Model::action()
punit/phpunit/src/Framework/TestCase.php:1400  - PMRAtk\tests\phpunit\Data\MessageForUserTest PMRAtk\tests\phpunit\Data\MessageForUserTest::testDateFilter()
```

As we all know, in "normal" addCondition (no OR case), its not a problem passing a DateTime object.

As a workaround i use:
```
            $messages->addCondition([
                ['created_date', '>=', $maxInPast->format('Y-m-d')],
                ['never_invalid', 1]
            ]);
```

### PR DESCRIPTION
**Pull request by DarkSide666**
Model condition now correctly typecasts also conditions passed as array (OR conditions).

fix #474 (see more precise description of bug there).

### CODE REVIEW

File: tests/ConditionSQLTest.php [hunk 1]
```diff
@@ -244,6 +244,29 @@ public function testDateCondition()
...
+        $this->setDB($a);
+
+        $m = new Model($this->db, 'user');
+        $m->addField('name');
+        $m->addField('date', ['type'=>'date']);
+
+        $m->addCondition('date', new \DateTime('08-12-1982'));
+        $m->loadAny();
+        $this->assertEquals('Sue', $m['name']);
+        $this->assertEquals('Sue', $m['name']);
```
Comment (PhilippGrashoff) [inline tests/ConditionSQLTest.php]: This line is a duplicate of the line before.

Comment (DarkSide666) [reply tests/ConditionSQLTest.php]: yeah :) will fix
