### PR TITLE
Fix initQueryFields (274)

### LINKED ISSUE #274: After latest composer update, warning is thrown in Persistence_SQL->initQueryFields()
After the latest update yesterday, I get a lot of Warnings about a invalid argument for foreach:
`<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/html/TourManagement/vendor/atk4/data/src/Persistence_SQL.php</b> on line <b>240</b><br />`

Comment says that the function initQueryFields parameter 3 is either an array (of fields) or null:
```
 /**
     * Adds model fields in Query.
     *
     * @param Model            $m
     * @param \atk4\dsql\Query $q
     * @param array|null       $fields
     */
```
If only an array or null are valid values for $fields, the following check could be changed from:
       ` if ($fields) {`
to
        `if (is_array($fields)) {`

This makes my warnings disappear.
The warning is caused by a lot of select functions like Model->tryLoad() or Model->export().

Best regards
Philipp

### PR DESCRIPTION
**Pull request by DarkSide666**
fix #274

### CODE REVIEW

File: src/Persistence_SQL.php [hunk 1]
```diff
@@ -233,7 +233,7 @@ public function initField($q, $field)
      */
     public function initQueryFields($m, $q, $fields = null)
     {
-        if ($fields) {
+        if (is_array($fields)) {
```
Comment (romaninsh) [inline src/Persistence_SQL.php]: maybe `is_array($fields) && $fields)`

Comment (DarkSide666) [reply src/Persistence_SQL.php]: `[]` should be the same as `false` - no fields
