### PR TITLE
Feature/fix join kind

### LINKED ISSUE #97: Join_SQL->kind doesn't pass to DSQL and it always use left join

### PR DESCRIPTION
**Pull request by DarkSide666**
fixes #97 and #98 

* Join_SQL forgot to set join kind for DSQL query at all.
* Join_SQL forgot that in case of nested joins it should look up table alias not in owner model, but in "previous" join foreign_table/foreign_alias.

### CODE REVIEW

File: src/Join_SQL.php [hunk 1]
```diff
@@ -119,9 +118,14 @@ public function initSelectQuery($model, $query)
...
+                    // if join is nested, then use previous join table alias
+                    ? (isset($this->join->foreign_alias) ? $this->join->foreign_alias : $this->join->foreign_table)
+                    // otherwise use owner model table alias
+                    : (isset($this->owner->table_alias) ? $this->owner->table_alias : $this->owner->table)
+                ).'.'.$this->master_field
+            ),
+            $this->kind
         );
 
         if ($this->reverse) {
```
Comment (DarkSide666) [inline src/Join_SQL.php]: Line next to this still looks suspicious. short_name = $this->join? really?
I have a feeling that something like I fixed few lines above should be there - with $this->join->foreign_alias/table if $this->join is set.
Please look into this before merging!

**Comment by romaninsh** [comment]
Does this resolve #82 ? Can we work a bit more to clean up multi-level joins here?

File: src/Join_SQL.php (hunk 1 above)
Comment (romaninsh) [inline src/Join_SQL.php]: there might be  a bit confusion. join is normally same as short_name. It was short_name originally. I think i started using ->join at some point or other way around but didn't complete. I think i will merge all of your PRs into single one, finish with joins add a bunch of test-scripts and then merge.

**Comment by romaninsh** [comment]
Noticed the lack of tests... ;)

**Comment by DarkSide666** [comment]
I'm not sure about #82 - have not tested that.

File: tests/JoinSQLTest.php [hunk 2]
```diff
@@ -378,4 +378,113 @@ public function testDoubleSaveHook()
...
+                2 => ['id'=>2, 'name'=>'US'],
+                3 => ['id'=>3, 'name'=>'India'],
+        ], ];
+        $this->setDB($a);
+
+        $db = new Persistence_SQL($this->db->connection);
+        $m_u = new Model($db, 'user');
+        $m_u->addField('contact_id');
+        $m_u->addField('name');
+        $j = $m_u->join('contact');
```
Comment (DarkSide666) [inline tests/JoinSQLTest.php]: Is this really reverse join?
